server:
  port: 8990

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/RequestDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27000
      database: employeeDB
      username: grup2
      password: Aa123456






