server:
  port: 8989

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  security:
    user:
      name: user
      password: 1234
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/AuthDB
     username: postgres
     password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

myapplication:
  feign:
    employee:
      employeeprofile: http://localhost:8990/employee